//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;

//using System.Xml.Linq;
//using Autodesk.AutoCAD.Runtime;
//using Autodesk.AutoCAD.DatabaseServices;
//using Autodesk.AutoCAD.ApplicationServices;
//using Autodesk.AutoCAD.EditorInput;
//using Autodesk.Civil.ApplicationServices;
//using Autodesk.Civil.DatabaseServices;

//namespace DryUtiltiesAutomator
//{
//    public class DraftClass
//    {


//        //[CommandMethod("za_Test")]

//        //public static void Test()
//        //{
//        //    Document doc = Application.DocumentManager.MdiActiveDocument;
//        //    CivilDocument civDoc = CivilApplication.ActiveDocument;
//        //    Database db = doc.Database;
//        //    Editor ed = doc.Editor;

//        //    // Ask the user to select a polyline
//        //    PromptEntityResult result = ed.GetEntity("Select a polyline:");
//        //    if (result.Status != PromptStatus.OK || result.ObjectId.IsNull)
//        //    {
//        //        ed.WriteMessage("\nError in selecting polyline.");
//        //        return;
//        //    }

//        //    using (Transaction tr = db.TransactionManager.StartTransaction())
//        //    {
//        //        try
//        //        {
                   


             
//        //            tr.Commit();


//        //            ed.WriteMessage("\n successfull.");
//        //        }
//        //        catch (System.Exception ex)
//        //        {
//        //            ed.WriteMessage("\nError: " + ex.Message);
//        //        }
//        //    }
//        //}
//    }
//}
